service: trilamb

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'development'}
  region: us-east-2

functions:
  graphql:
    handler: src/handler.graphql
    events:
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-apigw-binary

custom:
  serverless-offline:
    port: 3000
  apigwBinary:
    types:
      - 'multipart/form-data'
